### ISSUE TITLE
Allow to configure whole branch name (--name / new option)

### ISSUE THREAD

**Issue by blueyed** [anarcat/bup-cron#19]
Currently you can specify the `name`, which is used as base of the branch name:

    branch = '%s-%s' % (args.name, snapshot.src_path.replace('/', '_'))

Reading the help/code the `name` option makes a different impression, as if it would allow you to specify the whole name:

        # using the hostname as branch name
        group.add_argument('-n', '--name', default=socket.gethostname(),
                           help="""name of the backup passed to bup,
                                   defaults to hostname (%(default)s)""")

What do you think about keeping the current default, but use the name as-is when passed by `--name` (without the substituted path appended)?
(of course, this would be backwards-incompatible)

**Comment by anarcat** [comment]
how about a new --branch-name argument instead?

**Comment by blueyed** [comment]
Makes sense.
Will you add it or should I create a PR?

**Comment by anarcat** [comment]
please do :)
